# Generated by Django 5.1.4 on 2025-03-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField()),
                ('type', models.CharField(choices=[('CASH_IN', 'Cash In'), ('CASH_OUT', 'Cash Out'), ('DEBIT', 'Debit'), ('PAYMENT', 'Payment'), ('TRANSFER', 'Transfer')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('nameOrig', models.CharField(max_length=50)),
                ('oldbalanceOrg', models.DecimalField(decimal_places=2, max_digits=15)),
                ('newbalanceOrig', models.DecimalField(decimal_places=2, max_digits=15)),
                ('nameDest', models.CharField(max_length=50)),
                ('oldbalanceDest', models.DecimalField(decimal_places=2, max_digits=15)),
                ('newbalanceDest', models.DecimalField(decimal_places=2, max_digits=15)),
                ('isFraud', models.BooleanField(default=False)),
                ('isFlaggedFraud', models.BooleanField(default=False)),
                ('prediction_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
